### ISSUE TITLE
update_by_query function needed

### ISSUE THREAD

**Issue by karthi6023** [rtamizh/laravel-es#4]

**Comment by rtamizh** [comment]
@atlantis23 Can you use this 
```
Log::match('field', 'test')->script("doc['update_field'].value = update_value")->updateByQuery()
```
Try this in your test cluster and let me know if you find any problem. ( Don't test it on production )

**Comment by rtamizh** [comment]
@atlantis23 closing this for now. Open it back if you have issues with this.
